apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: disabled
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/olo42
    - Social:
      - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
          description: The front page of the internet

    - Entertainment:
      - YouTube:
        - abbr: YT
          href: https://youtube.com/
  services.yaml: |
    - Sites:
        - Webmail:
            href: https://mail.apck.de/
            description: Webmail for us
            # siteMonitor: https://mail.apck.de
            icon: roundcube.png
            ping: mail.apck.de

        - Vaultwarden:
            href: https://pass.apck.de/
            description: Our password manager
            icon: vaultwarden.png
            ping: pass.apck.de
        - Nextcloud:
            href: https://cloud.apck.de/
            description: Where your files get synced to
            icon: nextcloud.png
            ping: cloud.apck.de
    - Status Infos:
      - AdGuard:
          description: "Block advertisings"
          href: http://adguard.home.apck.de
          icon: adguard-home.png
          ping: http://adguard.home.apck.de
      - Bind DNS:
          description: "Local Bind DNS Server"
          icon: bind.png
          ping: dns.home.apck.de
      - Proxmox:
          description: "Virtualization"
          icon: proxmox.png
          href: https://pve.home.apck.de:8006
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
